# Release with JReleaser
# https://jreleaser.org/guide/latest/continuous-integration/github-actions.html

name: Build and test with Java CI, Maven, and JReleaser

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  release:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup the Java version
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'zulu'

      # Ensure Maven wrapper is executable
      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      # Build and run tests
      - name: Maven package
        run: |
          ./mvnw -ntp -B package
